# DS 3000/CS 3200 Lab 1

Due: Tuesday May 13 in-class

### Submission Instructions
Upload this `ipynb` file to GitHub, and then to Gradescope.  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to GitHub and verify that the correct version is represented on Gradescope.

### Tips for success
- Collaborate: bounce ideas off of each other, if you are having trouble you can ask your classmates or Dr. Gerber for help with specific issues, however...
- [(See)](http://www.northeastern.edu/osccr/academic-integrity), i.e. you are welcome to **talk about/discuss** (*not* show or allow each other to copy your answers to) the problems.

# Part 1 (40 points): Intro to Markdown

Use the markdown language below to create your own brief wikipedia-esque description of a topic related to International Government and Politics. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a **markdown** table of size at least 9 cells (i.e. 3 by 3, or 5 by 2)
- a list in **markdown**
- a link to another website

To practice typing in math mode, also include a LaTeX formula describing how your final grade is going to be calculated based on the syllabus, something like:

$$grade = weight_1*score_1 + weight_2*score_2$$

Please be **brief** in your text.  Aim for roughly 3 sentences total of text.

# International Government and Politics
![alt text](https://digitips.ch/wp-content/uploads/2023/09/International-Organisations-on-Social-Media-2023-1.png)
## Introduction:
    Government in the Europe differ from the governemtn in the US, yet both are connected through the use of NATO.
### Nato:
[Link to NATOS website](https://www.nato.int/)
    
    NATO is an aliance that connects the governements through transantlantic.
    Some countries in Nato include,
1. Belgium
2. USA
3. Canada
4. Denmark
5. ECT...

### European Countries 
    Here are some european countries and whether they affiliate with Nato
| Country | Affiliate with Nato |
|:--------:|:--------:|
|  Belgium   |  True   |
|  Austria  |  False   |
|  Spain   |  True   |



# Part 2: Numpy
## Part 2.1: Creating Arrays (10 points)

Create the following two arrays using the NumPy library and then print them out. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & -42 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

In [23]:
# make sure to import numpy library
import numpy as np
array_a = np.array([[3, 8, -2, 3],
                  [.5, -1, 6, 4],
                  [-5, 7, -42, 2]])

array_b = np.array([[42, 38, 34],
                  [30, 26, 22],
                  [18, 14, 10],
                  [6, 2, -2],
                  [-6, -10, -14]])


In [24]:
# uncomment below to print array_a
array_a

array([[  3. ,   8. ,  -2. ,   3. ],
       [  0.5,  -1. ,   6. ,   4. ],
       [ -5. ,   7. , -42. ,   2. ]])

In [25]:
# uncomment below to print array_b
array_b

array([[ 42,  38,  34],
       [ 30,  26,  22],
       [ 18,  14,  10],
       [  6,   2,  -2],
       [ -6, -10, -14]])

## Part 2.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b` (*prove* and *show* you did this with commented out code), then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [27]:
array_a.shape

(3, 4)

In [28]:
array_a.size

12

In [29]:
array_a.ndim

2

In [30]:
array_a.nbytes

96

In [31]:
array_b.shape

(5, 3)

In [32]:
array_b.size

15

In [33]:
array_b.ndim

2

In [34]:
array_b.nbytes

120

In [35]:
t_array_a = array_a.T
t_array_a

array([[  3. ,   0.5,  -5. ],
       [  8. ,  -1. ,   7. ],
       [ -2. ,   6. , -42. ],
       [  3. ,   4. ,   2. ]])

In [36]:
t_array_b = array_b.T
t_array_b

array([[ 42,  30,  18,   6,  -6],
       [ 38,  26,  14,   2, -10],
       [ 34,  22,  10,  -2, -14]])

In [37]:
# cant add because they don't have the same number of items
adding = array_a + t_array_b

ValueError: operands could not be broadcast together with shapes (3,4) (3,5) 

In [50]:
t_array_b_new = t_array_b[:, :-1]
adding2 = array_a + t_array_b_new
adding2

array([[ 45. ,  38. ,  16. ,   9. ],
       [ 38.5,  25. ,  20. ,   6. ],
       [ 29. ,  29. , -32. ,   0. ]])

# Part 3: Pandas
## Part 3.1: Reading in Data (5 points)

On Canvas is the `train_stations_europe.csv` file. It was adapted from [this Kaggle data set](https://www.kaggle.com/datasets/headsortails/train-stations-in-europe). Read this data set in, using the `id` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [9]:
# make sure to import pandas library
import pandas as pd

df_trainStations = pd.read_csv('train_stations_europe.csv' , encoding='unicode_escape')
df_trainStations.head()

id                     name   latitude  longitude  parent_station_id  \
0   1  Chateau-Arnoux-St-Auban  44.081790   6.001625                NaN   
1   2  Chateau-Arnoux-St-Auban  44.061565   5.997373                1.0   
2   3    Chateau-Arnoux Mairie  44.063863   6.011248                1.0   
3   4          Digne-les-Bains  44.350000   6.350000                NaN   
4   6          Digne-les-Bains  44.088710   6.222982                4.0   

  country     time_zone  is_city  is_main_station  is_airport  
0      FR  Europe/Paris     True            False       False  
1      FR  Europe/Paris    False             True       False  
2      FR  Europe/Paris    False            False       False  
3      FR  Europe/Paris     True            False       False  
4      FR  Europe/Paris    False             True       False

## Part 3.2: Manipulating Data (20 points)

1. Create a subset of the data set which (a) **includes** only train stations in Belgium and (b) **excludes** all train stations which are **not** in a city. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the subset from the previous part. Create a markdown cell and explain:
    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [52]:
train_stations = df_trainStations[
    (df_trainStations['country'] == 'BE') & 
    (df_trainStations['is_city'] == False)]

train_stations.head()

id               name   latitude  longitude  parent_station_id  \
892   1121  Tournai Frontiere        NaN        NaN                NaN   
893   1122          Froyennes        NaN        NaN                NaN   
993   1313           Mouscron        NaN        NaN                NaN   
1029  1354    Quevy Frontiere        NaN        NaN             6003.0   
4494  5893     Bruxelles-Midi  50.835374   4.335695             5974.0   

     country        time_zone  is_city  is_main_station  is_airport  
892       BE  Europe/Brussels    False            False       False  
893       BE  Europe/Brussels    False            False       False  
993       BE  Europe/Brussels    False            False       False  
1029      BE  Europe/Brussels    False            False       False  
4494      BE  Europe/Brussels    False             True       False

In [15]:
train_stations.describe()


id   latitude  longitude  parent_station_id
count     11.000000   9.000000   9.000000                0.0
mean   18741.363636  50.719715   4.810847                NaN
std    12582.067773   0.366820   0.996916                NaN
min     5964.000000  49.999779   3.263740                NaN
25%     5988.500000  50.617431   4.351739                NaN
50%    23044.000000  50.718089   4.444643                NaN
75%    29330.000000  50.979756   5.701847                NaN
max    35397.000000  51.221722   6.120155                NaN

The describe function works to use only the numerical values and exclues the non numerical values to get the count, mean, std, min, 25, 50, 75, and max of each set of numerical values.

# Part 4: GitHub (10 points)

When you finish the first three parts, give one last restart and run all to this file. Then, go to the [DS 3000 GitHub](https://github.com/eaegerber/ds3000_summer25), fork it and then clone it to your local machine. Then:

- In the forked and cloned ds3000_summer25 repo, make a new branch (`git checkout -b lab-upload`)
- Create a folder with your name (as Dr. Gerber did)
- Navigate to that folder and place this jupyter notebook inside
- Add the file as the change to be committed (`git add .\Lab1_MyName.ipynb`)
- Check `git status`, your changes should be staged
- Commit the changes with a short message (`git commit -m "My message"`)
- Push the repository to GitHub (`git push origin lab-upload`)
- Navigate the the GitHub in the browser and create a pull request
- Once the pull request is merged, you can delete your branch in the "Pull Requests" tab in the browser
- Finally, upload the Lab to Gradescope. When you do so, it will give you the option to do it via GitHub; do that.